/**
 * Chemiation - ???????????????? (1-118)
 * ???????? (K-Q / n=1..7)??????????????
 */

const CATEGORIES = {
  'reactive-nonmetal': { zh: '?????', color: '#38bdf8', glow: 'rgba(56, 189, 248, 0.4)' },
  'noble-gas': { zh: '????', color: '#c084fc', glow: 'rgba(192, 132, 252, 0.4)' },
  'alkali-metal': { zh: '???', color: '#f43f5e', glow: 'rgba(244, 63, 94, 0.4)' },
  'alkaline-earth': { zh: '????', color: '#fb923c', glow: 'rgba(251, 146, 60, 0.4)' },
  'metalloid': { zh: '???', color: '#34d399', glow: 'rgba(52, 211, 153, 0.4)' },
  'halogen': { zh: '??', color: '#22d3ee', glow: 'rgba(34, 211, 238, 0.4)' },
  'transition-metal': { zh: '????', color: '#818cf8', glow: 'rgba(129, 140, 248, 0.4)' },
  'post-transition': { zh: '?????', color: '#a3e635', glow: 'rgba(163, 230, 53, 0.4)' },
  'lanthanide': { zh: '????', color: '#e879f9', glow: 'rgba(232, 121, 249, 0.4)' },
  'actinide': { zh: '????', color: '#f472b6', glow: 'rgba(244, 114, 182, 0.4)' }
};

const SHELL_NAMES = ['K', 'L', 'M', 'N', 'O', 'P', 'Q'];

const PERIODIC_ELEMENTS = [
  {
    "number": 1,
    "symbol": "H",
    "name": "Hydrogen",
    "zhName": "氢",
    "pinyin": "q?ng",
    "mass": 1.008,
    "period": 1,
    "group": 1,
    "gridRow": 1,
    "gridCol": 1,
    "category": "reactive-nonmetal",
    "color": "#F1F5F9",
    "shells": [
      1
    ],
    "config": "1s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 2,
    "symbol": "He",
    "name": "Helium",
    "zhName": "氦",
    "pinyin": "h?i",
    "mass": 4.003,
    "period": 1,
    "group": 18,
    "gridRow": 1,
    "gridCol": 18,
    "category": "noble-gas",
    "color": "#64748B",
    "shells": [
      2
    ],
    "config": "1s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 3,
    "symbol": "Li",
    "name": "Lithium",
    "zhName": "锂",
    "pinyin": "l?",
    "mass": 6.94,
    "period": 2,
    "group": 1,
    "gridRow": 2,
    "gridCol": 1,
    "category": "alkali-metal",
    "color": "#CC80FF",
    "shells": [
      2,
      1
    ],
    "config": "[He] 2s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 4,
    "symbol": "Be",
    "name": "Beryllium",
    "zhName": "铍",
    "pinyin": "p?",
    "mass": 9.012,
    "period": 2,
    "group": 2,
    "gridRow": 2,
    "gridCol": 2,
    "category": "alkaline-earth",
    "color": "#C2FF00",
    "shells": [
      2,
      2
    ],
    "config": "[He] 2s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 5,
    "symbol": "B",
    "name": "Boron",
    "zhName": "硼",
    "pinyin": "p?ng",
    "mass": 10.81,
    "period": 2,
    "group": 13,
    "gridRow": 2,
    "gridCol": 13,
    "category": "metalloid",
    "color": "#FFB5B5",
    "shells": [
      2,
      3
    ],
    "config": "[He] 2s? 2p?",
    "valence": 3,
    "state": "??"
  },
  {
    "number": 6,
    "symbol": "C",
    "name": "Carbon",
    "zhName": "碳",
    "pinyin": "t?n",
    "mass": 12.011,
    "period": 2,
    "group": 14,
    "gridRow": 2,
    "gridCol": 14,
    "category": "reactive-nonmetal",
    "color": "#FACC15",
    "shells": [
      2,
      4
    ],
    "config": "[He] 2s? 2p?",
    "valence": 4,
    "state": "??"
  },
  {
    "number": 7,
    "symbol": "N",
    "name": "Nitrogen",
    "zhName": "氮",
    "pinyin": "d?n",
    "mass": 14.007,
    "period": 2,
    "group": 15,
    "gridRow": 2,
    "gridCol": 15,
    "category": "reactive-nonmetal",
    "color": "#22C55E",
    "shells": [
      2,
      5
    ],
    "config": "[He] 2s? 2p?",
    "valence": 5,
    "state": "??"
  },
  {
    "number": 8,
    "symbol": "O",
    "name": "Oxygen",
    "zhName": "氧",
    "pinyin": "y?ng",
    "mass": 15.999,
    "period": 2,
    "group": 16,
    "gridRow": 2,
    "gridCol": 16,
    "category": "reactive-nonmetal",
    "color": "#38BDF8",
    "shells": [
      2,
      6
    ],
    "config": "[He] 2s? 2p?",
    "valence": 6,
    "state": "??"
  },
  {
    "number": 9,
    "symbol": "F",
    "name": "Fluorine",
    "zhName": "氟",
    "pinyin": "f?",
    "mass": 18.998,
    "period": 2,
    "group": 17,
    "gridRow": 2,
    "gridCol": 17,
    "category": "halogen",
    "color": "#8B4513",
    "shells": [
      2,
      7
    ],
    "config": "[He] 2s? 2p?",
    "valence": 7,
    "state": "??"
  },
  {
    "number": 10,
    "symbol": "Ne",
    "name": "Neon",
    "zhName": "氖",
    "pinyin": "n?i",
    "mass": 20.18,
    "period": 2,
    "group": 18,
    "gridRow": 2,
    "gridCol": 18,
    "category": "noble-gas",
    "color": "#64748B",
    "shells": [
      2,
      8
    ],
    "config": "[He] 2s? 2p?",
    "valence": 8,
    "state": "??"
  },
  {
    "number": 11,
    "symbol": "Na",
    "name": "Sodium",
    "zhName": "钠",
    "pinyin": "n?",
    "mass": 22.99,
    "period": 3,
    "group": 1,
    "gridRow": 3,
    "gridCol": 1,
    "category": "alkali-metal",
    "color": "#AB5CF2",
    "shells": [
      2,
      8,
      1
    ],
    "config": "[Ne] 3s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 12,
    "symbol": "Mg",
    "name": "Magnesium",
    "zhName": "镁",
    "pinyin": "m?i",
    "mass": 24.305,
    "period": 3,
    "group": 2,
    "gridRow": 3,
    "gridCol": 2,
    "category": "alkaline-earth",
    "color": "#8AE234",
    "shells": [
      2,
      8,
      2
    ],
    "config": "[Ne] 3s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 13,
    "symbol": "Al",
    "name": "Aluminium",
    "zhName": "铝",
    "pinyin": "l?",
    "mass": 26.982,
    "period": 3,
    "group": 13,
    "gridRow": 3,
    "gridCol": 13,
    "category": "post-transition",
    "color": "#BFA6A6",
    "shells": [
      2,
      8,
      3
    ],
    "config": "[Ne] 3s? 3p?",
    "valence": 3,
    "state": "??"
  },
  {
    "number": 14,
    "symbol": "Si",
    "name": "Silicon",
    "zhName": "硅",
    "pinyin": "gu?",
    "mass": 28.085,
    "period": 3,
    "group": 14,
    "gridRow": 3,
    "gridCol": 14,
    "category": "metalloid",
    "color": "#F0C8A0",
    "shells": [
      2,
      8,
      4
    ],
    "config": "[Ne] 3s? 3p?",
    "valence": 4,
    "state": "??"
  },
  {
    "number": 15,
    "symbol": "P",
    "name": "Phosphorus",
    "zhName": "磷",
    "pinyin": "l?n",
    "mass": 30.974,
    "period": 3,
    "group": 15,
    "gridRow": 3,
    "gridCol": 15,
    "category": "reactive-nonmetal",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      5
    ],
    "config": "[Ne] 3s? 3p?",
    "valence": 5,
    "state": "??"
  },
  {
    "number": 16,
    "symbol": "S",
    "name": "Sulfur",
    "zhName": "硫",
    "pinyin": "li?",
    "mass": 32.06,
    "period": 3,
    "group": 16,
    "gridRow": 3,
    "gridCol": 16,
    "category": "reactive-nonmetal",
    "color": "#F97316",
    "shells": [
      2,
      8,
      6
    ],
    "config": "[Ne] 3s? 3p?",
    "valence": 6,
    "state": "??"
  },
  {
    "number": 17,
    "symbol": "Cl",
    "name": "Chlorine",
    "zhName": "氯",
    "pinyin": "l?",
    "mass": 35.45,
    "period": 3,
    "group": 17,
    "gridRow": 3,
    "gridCol": 17,
    "category": "halogen",
    "color": "#15803D",
    "shells": [
      2,
      8,
      7
    ],
    "config": "[Ne] 3s? 3p?",
    "valence": 7,
    "state": "??"
  },
  {
    "number": 18,
    "symbol": "Ar",
    "name": "Argon",
    "zhName": "氩",
    "pinyin": "y?",
    "mass": 39.95,
    "period": 3,
    "group": 18,
    "gridRow": 3,
    "gridCol": 18,
    "category": "noble-gas",
    "color": "#64748B",
    "shells": [
      2,
      8,
      8
    ],
    "config": "[Ne] 3s? 3p?",
    "valence": 8,
    "state": "??"
  },
  {
    "number": 19,
    "symbol": "K",
    "name": "Potassium",
    "zhName": "钾",
    "pinyin": "ji?",
    "mass": 39.098,
    "period": 4,
    "group": 1,
    "gridRow": 4,
    "gridCol": 1,
    "category": "alkali-metal",
    "color": "#8F40D4",
    "shells": [
      2,
      8,
      8,
      1
    ],
    "config": "[Ar] 4s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 20,
    "symbol": "Ca",
    "name": "Calcium",
    "zhName": "钙",
    "pinyin": "g?i",
    "mass": 40.078,
    "period": 4,
    "group": 2,
    "gridRow": 4,
    "gridCol": 2,
    "category": "alkaline-earth",
    "color": "#3DFF00",
    "shells": [
      2,
      8,
      8,
      2
    ],
    "config": "[Ar] 4s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 21,
    "symbol": "Sc",
    "name": "Scandium",
    "zhName": "钪",
    "pinyin": "k?ng",
    "mass": 44.956,
    "period": 4,
    "group": 3,
    "gridRow": 4,
    "gridCol": 3,
    "category": "transition-metal",
    "color": "#E6E6E6",
    "shells": [
      2,
      8,
      9,
      2
    ],
    "config": "[Ar] 3d? 4s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 22,
    "symbol": "Ti",
    "name": "Titanium",
    "zhName": "钛",
    "pinyin": "t?i",
    "mass": 47.867,
    "period": 4,
    "group": 4,
    "gridRow": 4,
    "gridCol": 4,
    "category": "transition-metal",
    "color": "#BFC2C7",
    "shells": [
      2,
      8,
      10,
      2
    ],
    "config": "[Ar] 3d? 4s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 23,
    "symbol": "V",
    "name": "Vanadium",
    "zhName": "钒",
    "pinyin": "f?n",
    "mass": 50.942,
    "period": 4,
    "group": 5,
    "gridRow": 4,
    "gridCol": 5,
    "category": "transition-metal",
    "color": "#A6A6AB",
    "shells": [
      2,
      8,
      11,
      2
    ],
    "config": "[Ar] 3d? 4s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 24,
    "symbol": "Cr",
    "name": "Chromium",
    "zhName": "铬",
    "pinyin": "g?",
    "mass": 51.996,
    "period": 4,
    "group": 6,
    "gridRow": 4,
    "gridCol": 6,
    "category": "transition-metal",
    "color": "#8A99C7",
    "shells": [
      2,
      8,
      13,
      1
    ],
    "config": "[Ar] 3d? 4s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 25,
    "symbol": "Mn",
    "name": "Manganese",
    "zhName": "锰",
    "pinyin": "m?ng",
    "mass": 54.938,
    "period": 4,
    "group": 7,
    "gridRow": 4,
    "gridCol": 7,
    "category": "transition-metal",
    "color": "#9C7AC7",
    "shells": [
      2,
      8,
      13,
      2
    ],
    "config": "[Ar] 3d? 4s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 26,
    "symbol": "Fe",
    "name": "Iron",
    "zhName": "铁",
    "pinyin": "ti?",
    "mass": 55.845,
    "period": 4,
    "group": 8,
    "gridRow": 4,
    "gridCol": 8,
    "category": "transition-metal",
    "color": "#E06633",
    "shells": [
      2,
      8,
      14,
      2
    ],
    "config": "[Ar] 3d? 4s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 27,
    "symbol": "Co",
    "name": "Cobalt",
    "zhName": "钴",
    "pinyin": "g?",
    "mass": 58.933,
    "period": 4,
    "group": 9,
    "gridRow": 4,
    "gridCol": 9,
    "category": "transition-metal",
    "color": "#0069D9",
    "shells": [
      2,
      8,
      15,
      2
    ],
    "config": "[Ar] 3d? 4s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 28,
    "symbol": "Ni",
    "name": "Nickel",
    "zhName": "镍",
    "pinyin": "ni?",
    "mass": 58.693,
    "period": 4,
    "group": 10,
    "gridRow": 4,
    "gridCol": 10,
    "category": "transition-metal",
    "color": "#50D050",
    "shells": [
      2,
      8,
      16,
      2
    ],
    "config": "[Ar] 3d? 4s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 29,
    "symbol": "Cu",
    "name": "Copper",
    "zhName": "铜",
    "pinyin": "t?ng",
    "mass": 63.546,
    "period": 4,
    "group": 11,
    "gridRow": 4,
    "gridCol": 11,
    "category": "transition-metal",
    "color": "#C88033",
    "shells": [
      2,
      8,
      18,
      1
    ],
    "config": "[Ar] 3d?? 4s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 30,
    "symbol": "Zn",
    "name": "Zinc",
    "zhName": "锌",
    "pinyin": "x?n",
    "mass": 65.38,
    "period": 4,
    "group": 12,
    "gridRow": 4,
    "gridCol": 12,
    "category": "transition-metal",
    "color": "#7D80B0",
    "shells": [
      2,
      8,
      18,
      2
    ],
    "config": "[Ar] 3d?? 4s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 31,
    "symbol": "Ga",
    "name": "Gallium",
    "zhName": "镓",
    "pinyin": "ji?",
    "mass": 69.723,
    "period": 4,
    "group": 13,
    "gridRow": 4,
    "gridCol": 13,
    "category": "post-transition",
    "color": "#C28F8F",
    "shells": [
      2,
      8,
      18,
      3
    ],
    "config": "[Ar] 3d?? 4s? 4p?",
    "valence": 3,
    "state": "??"
  },
  {
    "number": 32,
    "symbol": "Ge",
    "name": "Germanium",
    "zhName": "锗",
    "pinyin": "zh?",
    "mass": 72.63,
    "period": 4,
    "group": 14,
    "gridRow": 4,
    "gridCol": 14,
    "category": "metalloid",
    "color": "#668F8F",
    "shells": [
      2,
      8,
      18,
      4
    ],
    "config": "[Ar] 3d?? 4s? 4p?",
    "valence": 4,
    "state": "??"
  },
  {
    "number": 33,
    "symbol": "As",
    "name": "Arsenic",
    "zhName": "砷",
    "pinyin": "sh?n",
    "mass": 74.922,
    "period": 4,
    "group": 15,
    "gridRow": 4,
    "gridCol": 15,
    "category": "metalloid",
    "color": "#BD80E3",
    "shells": [
      2,
      8,
      18,
      5
    ],
    "config": "[Ar] 3d?? 4s? 4p?",
    "valence": 5,
    "state": "??"
  },
  {
    "number": 34,
    "symbol": "Se",
    "name": "Selenium",
    "zhName": "硒",
    "pinyin": "x?",
    "mass": 78.971,
    "period": 4,
    "group": 16,
    "gridRow": 4,
    "gridCol": 16,
    "category": "reactive-nonmetal",
    "color": "#FFA100",
    "shells": [
      2,
      8,
      18,
      6
    ],
    "config": "[Ar] 3d?? 4s? 4p?",
    "valence": 6,
    "state": "??"
  },
  {
    "number": 35,
    "symbol": "Br",
    "name": "Bromine",
    "zhName": "溴",
    "pinyin": "xi?",
    "mass": 79.904,
    "period": 4,
    "group": 17,
    "gridRow": 4,
    "gridCol": 17,
    "category": "halogen",
    "color": "#991B1B",
    "shells": [
      2,
      8,
      18,
      7
    ],
    "config": "[Ar] 3d?? 4s? 4p?",
    "valence": 7,
    "state": "??"
  },
  {
    "number": 36,
    "symbol": "Kr",
    "name": "Krypton",
    "zhName": "氪",
    "pinyin": "k?",
    "mass": 83.798,
    "period": 4,
    "group": 18,
    "gridRow": 4,
    "gridCol": 18,
    "category": "noble-gas",
    "color": "#64748B",
    "shells": [
      2,
      8,
      18,
      8
    ],
    "config": "[Ar] 3d?? 4s? 4p?",
    "valence": 8,
    "state": "??"
  },
  {
    "number": 37,
    "symbol": "Rb",
    "name": "Rubidium",
    "zhName": "铷",
    "pinyin": "r?",
    "mass": 85.468,
    "period": 5,
    "group": 1,
    "gridRow": 5,
    "gridCol": 1,
    "category": "alkali-metal",
    "color": "#702EB0",
    "shells": [
      2,
      8,
      18,
      8,
      1
    ],
    "config": "[Kr] 5s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 38,
    "symbol": "Sr",
    "name": "Strontium",
    "zhName": "锶",
    "pinyin": "s?",
    "mass": 87.62,
    "period": 5,
    "group": 2,
    "gridRow": 5,
    "gridCol": 2,
    "category": "alkaline-earth",
    "color": "#00FF00",
    "shells": [
      2,
      8,
      18,
      8,
      2
    ],
    "config": "[Kr] 5s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 39,
    "symbol": "Y",
    "name": "Yttrium",
    "zhName": "钇",
    "pinyin": "y?",
    "mass": 88.906,
    "period": 5,
    "group": 3,
    "gridRow": 5,
    "gridCol": 3,
    "category": "transition-metal",
    "color": "#94FFFF",
    "shells": [
      2,
      8,
      18,
      9,
      2
    ],
    "config": "[Kr] 4d? 5s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 40,
    "symbol": "Zr",
    "name": "Zirconium",
    "zhName": "锆",
    "pinyin": "g?o",
    "mass": 91.224,
    "period": 5,
    "group": 4,
    "gridRow": 5,
    "gridCol": 4,
    "category": "transition-metal",
    "color": "#94E0E0",
    "shells": [
      2,
      8,
      18,
      10,
      2
    ],
    "config": "[Kr] 4d? 5s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 41,
    "symbol": "Nb",
    "name": "Niobium",
    "zhName": "铌",
    "pinyin": "n?",
    "mass": 92.906,
    "period": 5,
    "group": 5,
    "gridRow": 5,
    "gridCol": 5,
    "category": "transition-metal",
    "color": "#73C2C9",
    "shells": [
      2,
      8,
      18,
      12,
      1
    ],
    "config": "[Kr] 4d? 5s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 42,
    "symbol": "Mo",
    "name": "Molybdenum",
    "zhName": "钼",
    "pinyin": "m?",
    "mass": 95.95,
    "period": 5,
    "group": 6,
    "gridRow": 5,
    "gridCol": 6,
    "category": "transition-metal",
    "color": "#54B5B5",
    "shells": [
      2,
      8,
      18,
      13,
      1
    ],
    "config": "[Kr] 4d? 5s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 43,
    "symbol": "Tc",
    "name": "Technetium",
    "zhName": "锝",
    "pinyin": "d?",
    "mass": 98.0,
    "period": 5,
    "group": 7,
    "gridRow": 5,
    "gridCol": 7,
    "category": "transition-metal",
    "color": "#3B9E9E",
    "shells": [
      2,
      8,
      18,
      13,
      2
    ],
    "config": "[Kr] 4d? 5s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 44,
    "symbol": "Ru",
    "name": "Ruthenium",
    "zhName": "钌",
    "pinyin": "li?o",
    "mass": 101.07,
    "period": 5,
    "group": 8,
    "gridRow": 5,
    "gridCol": 8,
    "category": "transition-metal",
    "color": "#248F8F",
    "shells": [
      2,
      8,
      18,
      15,
      1
    ],
    "config": "[Kr] 4d? 5s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 45,
    "symbol": "Rh",
    "name": "Rhodium",
    "zhName": "铑",
    "pinyin": "l?o",
    "mass": 102.91,
    "period": 5,
    "group": 9,
    "gridRow": 5,
    "gridCol": 9,
    "category": "transition-metal",
    "color": "#0A7D8C",
    "shells": [
      2,
      8,
      18,
      16,
      1
    ],
    "config": "[Kr] 4d? 5s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 46,
    "symbol": "Pd",
    "name": "Palladium",
    "zhName": "钯",
    "pinyin": "b?",
    "mass": 106.42,
    "period": 5,
    "group": 10,
    "gridRow": 5,
    "gridCol": 10,
    "category": "transition-metal",
    "color": "#006985",
    "shells": [
      2,
      8,
      18,
      18,
      0
    ],
    "config": "[Kr] 4d??",
    "valence": 0,
    "state": "??"
  },
  {
    "number": 47,
    "symbol": "Ag",
    "name": "Silver",
    "zhName": "银",
    "pinyin": "y?n",
    "mass": 107.87,
    "period": 5,
    "group": 11,
    "gridRow": 5,
    "gridCol": 11,
    "category": "transition-metal",
    "color": "#C0C0C0",
    "shells": [
      2,
      8,
      18,
      18,
      1
    ],
    "config": "[Kr] 4d?? 5s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 48,
    "symbol": "Cd",
    "name": "Cadmium",
    "zhName": "镉",
    "pinyin": "g?",
    "mass": 112.41,
    "period": 5,
    "group": 12,
    "gridRow": 5,
    "gridCol": 12,
    "category": "transition-metal",
    "color": "#FFD98F",
    "shells": [
      2,
      8,
      18,
      18,
      2
    ],
    "config": "[Kr] 4d?? 5s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 49,
    "symbol": "In",
    "name": "Indium",
    "zhName": "铟",
    "pinyin": "y?n",
    "mass": 114.82,
    "period": 5,
    "group": 13,
    "gridRow": 5,
    "gridCol": 13,
    "category": "post-transition",
    "color": "#A67573",
    "shells": [
      2,
      8,
      18,
      18,
      3
    ],
    "config": "[Kr] 4d?? 5s? 5p?",
    "valence": 3,
    "state": "??"
  },
  {
    "number": 50,
    "symbol": "Sn",
    "name": "Tin",
    "zhName": "锡",
    "pinyin": "x?",
    "mass": 118.71,
    "period": 5,
    "group": 14,
    "gridRow": 5,
    "gridCol": 14,
    "category": "post-transition",
    "color": "#668080",
    "shells": [
      2,
      8,
      18,
      18,
      4
    ],
    "config": "[Kr] 4d?? 5s? 5p?",
    "valence": 4,
    "state": "??"
  },
  {
    "number": 51,
    "symbol": "Sb",
    "name": "Antimony",
    "zhName": "锑",
    "pinyin": "t?",
    "mass": 121.76,
    "period": 5,
    "group": 15,
    "gridRow": 5,
    "gridCol": 15,
    "category": "metalloid",
    "color": "#9E63B5",
    "shells": [
      2,
      8,
      18,
      18,
      5
    ],
    "config": "[Kr] 4d?? 5s? 5p?",
    "valence": 5,
    "state": "??"
  },
  {
    "number": 52,
    "symbol": "Te",
    "name": "Tellurium",
    "zhName": "碲",
    "pinyin": "d?",
    "mass": 127.6,
    "period": 5,
    "group": 16,
    "gridRow": 5,
    "gridCol": 16,
    "category": "metalloid",
    "color": "#D47A00",
    "shells": [
      2,
      8,
      18,
      18,
      6
    ],
    "config": "[Kr] 4d?? 5s? 5p?",
    "valence": 6,
    "state": "??"
  },
  {
    "number": 53,
    "symbol": "I",
    "name": "Iodine",
    "zhName": "碘",
    "pinyin": "di?n",
    "mass": 126.9,
    "period": 5,
    "group": 17,
    "gridRow": 5,
    "gridCol": 17,
    "category": "halogen",
    "color": "#6B21A8",
    "shells": [
      2,
      8,
      18,
      18,
      7
    ],
    "config": "[Kr] 4d?? 5s? 5p?",
    "valence": 7,
    "state": "??"
  },
  {
    "number": 54,
    "symbol": "Xe",
    "name": "Xenon",
    "zhName": "氙",
    "pinyin": "xi?n",
    "mass": 131.29,
    "period": 5,
    "group": 18,
    "gridRow": 5,
    "gridCol": 18,
    "category": "noble-gas",
    "color": "#64748B",
    "shells": [
      2,
      8,
      18,
      18,
      8
    ],
    "config": "[Kr] 4d?? 5s? 5p?",
    "valence": 8,
    "state": "??"
  },
  {
    "number": 55,
    "symbol": "Cs",
    "name": "Caesium",
    "zhName": "铯",
    "pinyin": "s?",
    "mass": 132.91,
    "period": 6,
    "group": 1,
    "gridRow": 6,
    "gridCol": 1,
    "category": "alkali-metal",
    "color": "#57178F",
    "shells": [
      2,
      8,
      18,
      18,
      8,
      1
    ],
    "config": "[Xe] 6s?",
    "valence": 1,
    "state": "??"
  },
  {
    "number": 56,
    "symbol": "Ba",
    "name": "Barium",
    "zhName": "钡",
    "pinyin": "b?i",
    "mass": 137.33,
    "period": 6,
    "group": 2,
    "gridRow": 6,
    "gridCol": 2,
    "category": "alkaline-earth",
    "color": "#00C900",
    "shells": [
      2,
      8,
      18,
      18,
      8,
      2
    ],
    "config": "[Xe] 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 72,
    "symbol": "Hf",
    "name": "Hafnium",
    "zhName": "铪",
    "pinyin": "l?n",
    "mass": 178.49,
    "period": 6,
    "group": 4,
    "gridRow": 6,
    "gridCol": 4,
    "category": "transition-metal",
    "color": "#4DC2FF",
    "shells": [
      2,
      8,
      18,
      18,
      9,
      2
    ],
    "config": "[Xe] 5d? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 73,
    "symbol": "Ta",
    "name": "Tantalum",
    "zhName": "钽",
    "pinyin": "sh?",
    "mass": 180.95,
    "period": 6,
    "group": 5,
    "gridRow": 6,
    "gridCol": 5,
    "category": "transition-metal",
    "color": "#4DA6FF",
    "shells": [
      2,
      8,
      18,
      19,
      9,
      2
    ],
    "config": "[Xe] 4f? 5d? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 74,
    "symbol": "W",
    "name": "Tungsten",
    "zhName": "钨",
    "pinyin": "cu?",
    "mass": 183.84,
    "period": 6,
    "group": 6,
    "gridRow": 6,
    "gridCol": 6,
    "category": "transition-metal",
    "color": "#2194D6",
    "shells": [
      2,
      8,
      18,
      21,
      8,
      2
    ],
    "config": "[Xe] 4f? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 75,
    "symbol": "Re",
    "name": "Rhenium",
    "zhName": "铼",
    "pinyin": "n?",
    "mass": 186.21,
    "period": 6,
    "group": 7,
    "gridRow": 6,
    "gridCol": 7,
    "category": "transition-metal",
    "color": "#267DAB",
    "shells": [
      2,
      8,
      18,
      22,
      8,
      2
    ],
    "config": "[Xe] 4f? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 76,
    "symbol": "Os",
    "name": "Osmium",
    "zhName": "锇",
    "pinyin": "p?",
    "mass": 190.23,
    "period": 6,
    "group": 8,
    "gridRow": 6,
    "gridCol": 8,
    "category": "transition-metal",
    "color": "#266696",
    "shells": [
      2,
      8,
      18,
      23,
      8,
      2
    ],
    "config": "[Xe] 4f? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 77,
    "symbol": "Ir",
    "name": "Iridium",
    "zhName": "铱",
    "pinyin": "sh?n",
    "mass": 192.22,
    "period": 6,
    "group": 9,
    "gridRow": 6,
    "gridCol": 9,
    "category": "transition-metal",
    "color": "#175487",
    "shells": [
      2,
      8,
      18,
      24,
      8,
      2
    ],
    "config": "[Xe] 4f? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 78,
    "symbol": "Pt",
    "name": "Platinum",
    "zhName": "铂",
    "pinyin": "y?u",
    "mass": 195.08,
    "period": 6,
    "group": 10,
    "gridRow": 6,
    "gridCol": 10,
    "category": "transition-metal",
    "color": "#D0D0E0",
    "shells": [
      2,
      8,
      18,
      25,
      8,
      2
    ],
    "config": "[Xe] 4f? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 79,
    "symbol": "Au",
    "name": "Gold",
    "zhName": "金",
    "pinyin": "g?",
    "mass": 196.97,
    "period": 6,
    "group": 11,
    "gridRow": 6,
    "gridCol": 11,
    "category": "transition-metal",
    "color": "#FFD700",
    "shells": [
      2,
      8,
      18,
      25,
      9,
      2
    ],
    "config": "[Xe] 4f? 5d? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 80,
    "symbol": "Hg",
    "name": "Mercury",
    "zhName": "汞",
    "pinyin": "t?",
    "mass": 200.59,
    "period": 6,
    "group": 12,
    "gridRow": 6,
    "gridCol": 12,
    "category": "transition-metal",
    "color": "#B8B8D0",
    "shells": [
      2,
      8,
      18,
      27,
      8,
      2
    ],
    "config": "[Xe] 4f? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 81,
    "symbol": "Tl",
    "name": "Thallium",
    "zhName": "铊",
    "pinyin": "d?",
    "mass": 204.38,
    "period": 6,
    "group": 13,
    "gridRow": 6,
    "gridCol": 13,
    "category": "post-transition",
    "color": "#A6544D",
    "shells": [
      2,
      8,
      18,
      28,
      8,
      2
    ],
    "config": "[Xe] 4f?? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 82,
    "symbol": "Pb",
    "name": "Lead",
    "zhName": "铅",
    "pinyin": "hu?",
    "mass": 207.2,
    "period": 6,
    "group": 14,
    "gridRow": 6,
    "gridCol": 14,
    "category": "post-transition",
    "color": "#575961",
    "shells": [
      2,
      8,
      18,
      29,
      8,
      2
    ],
    "config": "[Xe] 4f?? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 83,
    "symbol": "Bi",
    "name": "Bismuth",
    "zhName": "铋",
    "pinyin": "?r",
    "mass": 208.98,
    "period": 6,
    "group": 15,
    "gridRow": 6,
    "gridCol": 15,
    "category": "post-transition",
    "color": "#9E4FB5",
    "shells": [
      2,
      8,
      18,
      30,
      8,
      2
    ],
    "config": "[Xe] 4f?? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 84,
    "symbol": "Po",
    "name": "Polonium",
    "zhName": "钋",
    "pinyin": "di?",
    "mass": 209.0,
    "period": 6,
    "group": 16,
    "gridRow": 6,
    "gridCol": 16,
    "category": "metalloid",
    "color": "#AB5C00",
    "shells": [
      2,
      8,
      18,
      31,
      8,
      2
    ],
    "config": "[Xe] 4f?? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 85,
    "symbol": "At",
    "name": "Astatine",
    "zhName": "砹",
    "pinyin": "y?",
    "mass": 210.0,
    "period": 6,
    "group": 17,
    "gridRow": 6,
    "gridCol": 17,
    "category": "halogen",
    "color": "#754F45",
    "shells": [
      2,
      8,
      18,
      32,
      8,
      2
    ],
    "config": "[Xe] 4f?? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 86,
    "symbol": "Rn",
    "name": "Radon",
    "zhName": "氡",
    "pinyin": "l?",
    "mass": 222.0,
    "period": 6,
    "group": 18,
    "gridRow": 6,
    "gridCol": 18,
    "category": "noble-gas",
    "color": "#64748B",
    "shells": [
      2,
      8,
      18,
      32,
      9,
      2
    ],
    "config": "[Xe] 4f?? 5d? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 87,
    "symbol": "Fr",
    "name": "Francium",
    "zhName": "钫",
    "pinyin": "h?",
    "mass": 223.0,
    "period": 7,
    "group": 1,
    "gridRow": 7,
    "gridCol": 1,
    "category": "alkali-metal",
    "color": "#420066",
    "shells": [
      2,
      8,
      18,
      32,
      10,
      2
    ],
    "config": "[Xe] 4f?? 5d? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 88,
    "symbol": "Ra",
    "name": "Radium",
    "zhName": "镭",
    "pinyin": "t?n",
    "mass": 226.0,
    "period": 7,
    "group": 2,
    "gridRow": 7,
    "gridCol": 2,
    "category": "alkaline-earth",
    "color": "#007D00",
    "shells": [
      2,
      8,
      18,
      32,
      11,
      2
    ],
    "config": "[Xe] 4f?? 5d? 6s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 104,
    "symbol": "Rf",
    "name": "Rutherfordium",
    "zhName": "𬬻",
    "pinyin": "w?",
    "mass": 267.0,
    "period": 7,
    "group": 4,
    "gridRow": 7,
    "gridCol": 4,
    "category": "transition-metal",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      12,
      2
    ],
    "config": "[Xe] 4f?? 5d? 6s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 105,
    "symbol": "Db",
    "name": "Dubnium",
    "zhName": "𬭊",
    "pinyin": "l?i",
    "mass": 268.0,
    "period": 7,
    "group": 5,
    "gridRow": 7,
    "gridCol": 5,
    "category": "transition-metal",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      13,
      2
    ],
    "config": "[Xe] 4f?? 5d? 6s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 106,
    "symbol": "Sg",
    "name": "Seaborgium",
    "zhName": "𬭳",
    "pinyin": "?",
    "mass": 269.0,
    "period": 7,
    "group": 6,
    "gridRow": 7,
    "gridCol": 6,
    "category": "transition-metal",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      14,
      2
    ],
    "config": "[Xe] 4f?? 5d? 6s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 107,
    "symbol": "Bh",
    "name": "Bohrium",
    "zhName": "𬭛",
    "pinyin": "y?",
    "mass": 270.0,
    "period": 7,
    "group": 7,
    "gridRow": 7,
    "gridCol": 7,
    "category": "transition-metal",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      15,
      2
    ],
    "config": "[Xe] 4f?? 5d? 6s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 108,
    "symbol": "Hs",
    "name": "Hassium",
    "zhName": "𬭶",
    "pinyin": "b?i",
    "mass": 277.0,
    "period": 7,
    "group": 8,
    "gridRow": 7,
    "gridCol": 8,
    "category": "transition-metal",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      17,
      1
    ],
    "config": "[Xe] 4f?? 5d? 6s?",
    "valence": 1,
    "state": "????"
  },
  {
    "number": 109,
    "symbol": "Mt",
    "name": "Meitnerium",
    "zhName": "鿏",
    "pinyin": "j?n",
    "mass": 278.0,
    "period": 7,
    "group": 9,
    "gridRow": 7,
    "gridCol": 9,
    "category": "transition-metal",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      1
    ],
    "config": "[Xe] 4f?? 5d?? 6s?",
    "valence": 1,
    "state": "????"
  },
  {
    "number": 110,
    "symbol": "Ds",
    "name": "Darmstadtium",
    "zhName": "𫟼",
    "pinyin": "g?ng",
    "mass": 281.0,
    "period": 7,
    "group": 10,
    "gridRow": 7,
    "gridCol": 10,
    "category": "transition-metal",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      2
    ],
    "config": "[Xe] 4f?? 5d?? 6s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 111,
    "symbol": "Rg",
    "name": "Roentgenium",
    "zhName": "𬬭",
    "pinyin": "t?",
    "mass": 282.0,
    "period": 7,
    "group": 11,
    "gridRow": 7,
    "gridCol": 11,
    "category": "transition-metal",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      3
    ],
    "config": "[Xe] 4f?? 5d?? 6s? 6p?",
    "valence": 3,
    "state": "????"
  },
  {
    "number": 112,
    "symbol": "Cn",
    "name": "Copernicium",
    "zhName": "鎶",
    "pinyin": "qi?n",
    "mass": 285.0,
    "period": 7,
    "group": 12,
    "gridRow": 7,
    "gridCol": 12,
    "category": "transition-metal",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      4
    ],
    "config": "[Xe] 4f?? 5d?? 6s? 6p?",
    "valence": 4,
    "state": "????"
  },
  {
    "number": 113,
    "symbol": "Nh",
    "name": "Nihonium",
    "zhName": "鿭",
    "pinyin": "b?",
    "mass": 286.0,
    "period": 7,
    "group": 13,
    "gridRow": 7,
    "gridCol": 13,
    "category": "post-transition",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      5
    ],
    "config": "[Xe] 4f?? 5d?? 6s? 6p?",
    "valence": 5,
    "state": "????"
  },
  {
    "number": 114,
    "symbol": "Fl",
    "name": "Flerovium",
    "zhName": "𫓧",
    "pinyin": "p?",
    "mass": 289.0,
    "period": 7,
    "group": 14,
    "gridRow": 7,
    "gridCol": 14,
    "category": "post-transition",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      6
    ],
    "config": "[Xe] 4f?? 5d?? 6s? 6p?",
    "valence": 6,
    "state": "????"
  },
  {
    "number": 115,
    "symbol": "Mc",
    "name": "Moscovium",
    "zhName": "镆",
    "pinyin": "?i",
    "mass": 290.0,
    "period": 7,
    "group": 15,
    "gridRow": 7,
    "gridCol": 15,
    "category": "post-transition",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      7
    ],
    "config": "[Xe] 4f?? 5d?? 6s? 6p?",
    "valence": 7,
    "state": "????"
  },
  {
    "number": 116,
    "symbol": "Lv",
    "name": "Livermorium",
    "zhName": "𫟷",
    "pinyin": "d?ng",
    "mass": 293.0,
    "period": 7,
    "group": 16,
    "gridRow": 7,
    "gridCol": 16,
    "category": "post-transition",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      8
    ],
    "config": "[Xe] 4f?? 5d?? 6s? 6p?",
    "valence": 8,
    "state": "????"
  },
  {
    "number": 117,
    "symbol": "Ts",
    "name": "Tennessine",
    "zhName": "鿬",
    "pinyin": "f?",
    "mass": 294.0,
    "period": 7,
    "group": 17,
    "gridRow": 7,
    "gridCol": 17,
    "category": "halogen",
    "color": "#475569",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      8,
      1
    ],
    "config": "[Rn] 7s?",
    "valence": 1,
    "state": "????"
  },
  {
    "number": 118,
    "symbol": "Og",
    "name": "Oganesson",
    "zhName": "气奥",
    "pinyin": "l?i",
    "mass": 294.0,
    "period": 7,
    "group": 18,
    "gridRow": 7,
    "gridCol": 18,
    "category": "noble-gas",
    "color": "#64748B",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      8,
      2
    ],
    "config": "[Rn] 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 57,
    "symbol": "La",
    "name": "Lanthanum",
    "zhName": "镧",
    "pinyin": "?",
    "mass": 138.91,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 3,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      9,
      2
    ],
    "config": "[Rn] 6d? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 58,
    "symbol": "Ce",
    "name": "Cerium",
    "zhName": "铈",
    "pinyin": "t?",
    "mass": 140.12,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 4,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      10,
      2
    ],
    "config": "[Rn] 6d? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 59,
    "symbol": "Pr",
    "name": "Praseodymium",
    "zhName": "镨",
    "pinyin": "p?",
    "mass": 140.91,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 5,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      20,
      9,
      2
    ],
    "config": "[Rn] 5f? 6d? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 60,
    "symbol": "Nd",
    "name": "Neodymium",
    "zhName": "钕",
    "pinyin": "y?u",
    "mass": 144.24,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 6,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      21,
      9,
      2
    ],
    "config": "[Rn] 5f? 6d? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 61,
    "symbol": "Pm",
    "name": "Promethium",
    "zhName": "钷",
    "pinyin": "n?",
    "mass": 145.0,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 7,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      22,
      9,
      2
    ],
    "config": "[Rn] 5f? 6d? 7s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 62,
    "symbol": "Sm",
    "name": "Samarium",
    "zhName": "钐",
    "pinyin": "b?",
    "mass": 150.36,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 8,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      24,
      8,
      2
    ],
    "config": "[Rn] 5f? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 63,
    "symbol": "Eu",
    "name": "Europium",
    "zhName": "铕",
    "pinyin": "m?i",
    "mass": 151.96,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 9,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      25,
      8,
      2
    ],
    "config": "[Rn] 5f? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 64,
    "symbol": "Gd",
    "name": "Gadolinium",
    "zhName": "钆",
    "pinyin": "j?",
    "mass": 157.25,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 10,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      25,
      9,
      2
    ],
    "config": "[Rn] 5f? 6d? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 65,
    "symbol": "Tb",
    "name": "Terbium",
    "zhName": "铽",
    "pinyin": "p?i",
    "mass": 158.93,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 11,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      27,
      8,
      2
    ],
    "config": "[Rn] 5f? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 66,
    "symbol": "Dy",
    "name": "Dysprosium",
    "zhName": "镝",
    "pinyin": "k?i",
    "mass": 162.5,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 12,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      28,
      8,
      2
    ],
    "config": "[Rn] 5f?? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 67,
    "symbol": "Ho",
    "name": "Holmium",
    "zhName": "钬",
    "pinyin": "?i",
    "mass": 164.93,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 13,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      29,
      8,
      2
    ],
    "config": "[Rn] 5f?? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 68,
    "symbol": "Er",
    "name": "Erbium",
    "zhName": "铒",
    "pinyin": "f?i",
    "mass": 167.26,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 14,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      30,
      8,
      2
    ],
    "config": "[Rn] 5f?? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 69,
    "symbol": "Tm",
    "name": "Thulium",
    "zhName": "铥",
    "pinyin": "m?n",
    "mass": 168.93,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 15,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      31,
      8,
      2
    ],
    "config": "[Rn] 5f?? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 70,
    "symbol": "Yb",
    "name": "Ytterbium",
    "zhName": "镱",
    "pinyin": "nu?",
    "mass": 173.05,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 16,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      8,
      2
    ],
    "config": "[Rn] 5f?? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 71,
    "symbol": "Lu",
    "name": "Lutetium",
    "zhName": "镥",
    "pinyin": "l?o",
    "mass": 174.97,
    "period": 6,
    "group": 3,
    "gridRow": 8,
    "gridCol": 17,
    "category": "lanthanide",
    "color": "#F43F5E",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      8,
      3
    ],
    "config": "[Rn] 5f?? 7s? 7p?",
    "valence": 3,
    "state": "??"
  },
  {
    "number": 89,
    "symbol": "Ac",
    "name": "Actinium",
    "zhName": "锕",
    "pinyin": "l?",
    "mass": 227.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 3,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      10,
      2
    ],
    "config": "[Rn] 5f?? 6d? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 90,
    "symbol": "Th",
    "name": "Thorium",
    "zhName": "钍",
    "pinyin": "d?",
    "mass": 232.04,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 4,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      11,
      2
    ],
    "config": "[Rn] 5f?? 6d? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 91,
    "symbol": "Pa",
    "name": "Protactinium",
    "zhName": "镤",
    "pinyin": "x?",
    "mass": 231.04,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 5,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      12,
      2
    ],
    "config": "[Rn] 5f?? 6d? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 92,
    "symbol": "U",
    "name": "Uranium",
    "zhName": "铀",
    "pinyin": "b?",
    "mass": 238.03,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 6,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      13,
      2
    ],
    "config": "[Rn] 5f?? 6d? 7s?",
    "valence": 2,
    "state": "??"
  },
  {
    "number": 93,
    "symbol": "Np",
    "name": "Neptunium",
    "zhName": "镎",
    "pinyin": "h?i",
    "mass": 237.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 7,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      14,
      2
    ],
    "config": "[Rn] 5f?? 6d? 7s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 94,
    "symbol": "Pu",
    "name": "Plutonium",
    "zhName": "钚",
    "pinyin": "m?i",
    "mass": 244.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 8,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      15,
      2
    ],
    "config": "[Rn] 5f?? 6d? 7s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 95,
    "symbol": "Am",
    "name": "Americium",
    "zhName": "镅",
    "pinyin": "d?",
    "mass": 243.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 9,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      16,
      2
    ],
    "config": "[Rn] 5f?? 6d? 7s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 96,
    "symbol": "Cm",
    "name": "Curium",
    "zhName": "锔",
    "pinyin": "l?n",
    "mass": 247.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 10,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      17,
      2
    ],
    "config": "[Rn] 5f?? 6d? 7s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 97,
    "symbol": "Bk",
    "name": "Berkelium",
    "zhName": "锫",
    "pinyin": "g?",
    "mass": 247.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 11,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      2
    ],
    "config": "[Rn] 5f?? 6d?? 7s?",
    "valence": 2,
    "state": "????"
  },
  {
    "number": 98,
    "symbol": "Cf",
    "name": "Californium",
    "zhName": "锎",
    "pinyin": "n?",
    "mass": 251.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 12,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      3
    ],
    "config": "[Rn] 5f?? 6d?? 7s? 7p?",
    "valence": 3,
    "state": "????"
  },
  {
    "number": 99,
    "symbol": "Es",
    "name": "Einsteinium",
    "zhName": "锿",
    "pinyin": "f?",
    "mass": 252.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 13,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      4
    ],
    "config": "[Rn] 5f?? 6d?? 7s? 7p?",
    "valence": 4,
    "state": "????"
  },
  {
    "number": 100,
    "symbol": "Fm",
    "name": "Fermium",
    "zhName": "镄",
    "pinyin": "m?",
    "mass": 257.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 14,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      5
    ],
    "config": "[Rn] 5f?? 6d?? 7s? 7p?",
    "valence": 5,
    "state": "????"
  },
  {
    "number": 101,
    "symbol": "Md",
    "name": "Mendelevium",
    "zhName": "钔",
    "pinyin": "l?",
    "mass": 258.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 15,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      6
    ],
    "config": "[Rn] 5f?? 6d?? 7s? 7p?",
    "valence": 6,
    "state": "????"
  },
  {
    "number": 102,
    "symbol": "No",
    "name": "Nobelium",
    "zhName": "锘",
    "pinyin": "ti?n",
    "mass": 259.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 16,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      7
    ],
    "config": "[Rn] 5f?? 6d?? 7s? 7p?",
    "valence": 7,
    "state": "????"
  },
  {
    "number": 103,
    "symbol": "Lr",
    "name": "Lawrencium",
    "zhName": "铹",
    "pinyin": "?o",
    "mass": 266.0,
    "period": 7,
    "group": 3,
    "gridRow": 9,
    "gridCol": 17,
    "category": "actinide",
    "color": "#EC4899",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      8
    ],
    "config": "[Rn] 5f?? 6d?? 7s? 7p?",
    "valence": 8,
    "state": "????"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PERIODIC_ELEMENTS, CATEGORIES, SHELL_NAMES };
}
